services:
  novaxis:
    image: novosadkry/novaxis
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novaxis-discord
    tty: true
    stdin_open: true
    depends_on:
      - bgutil-provider
    volumes:
      - ./NOVAxis/config.json:/app/config.json
      - ./NOVAxis/keys:/app/keys
    ports:
      - "5000:5000"
    restart: unless-stopped
    logging:
      options:
        max-size: 50m

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:1.3.2
    container_name: novaxis-bgutil-provider
    init: true
    expose:
      - 4416
    restart: unless-stopped
    logging:
      options:
        max-size: 50m

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink
    container_name: novaxis-lavalink
    profiles:
      - lavalink
    volumes:
      - ./NOVAxis/Lavalink/application.yml:/opt/Lavalink/application.yml
      - ./NOVAxis/Lavalink/plugins:/opt/Lavalink/plugins
    expose:
      - 2333
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
