name: CI/CD Pipeline

on:
  push:
    tags:
      - v*

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  publish:
    uses: ./.github/workflows/publish.yml
    needs: [compile]

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [publish]