name: Build and Test

on:
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        configuration: [Debug, Release]

    name: Build and Test
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Fetch NuGet packages from cache
    - name: Restore package cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    # Restore the application to install all dependencies
    - name: Install dependencies
      run: dotnet restore

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --no-restore --verbosity normal
      
    # Build on all platforms and configurations
    - name: Build ${{ matrix.configuration }} on ${{ matrix.os }}
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
