name: Deploy to Production

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
    secrets:
      PROD_HOST:
        required: true
      PROD_USER:
        required: true
      PROD_SSH_KEY:
        required: true

concurrency: production

jobs:
  update_runner:
    name: Update production environment
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Replace Docker container
      uses: appleboy/ssh-action@master
      env:
        TAG: ${{ inputs.tag || github.ref_name }}
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        passphrase: ${{ secrets.PROD_SSH_PASS }}
        envs: TAG
        script: |
          cd ./files/novaxis/
          sudo -E docker-compose down
          sudo -E docker-compose pull
          sudo -E docker-compose up -d
