name: Publish Release

on:
  workflow_call:
    inputs:
      publish_github:
        required: false
        default: true
        type: boolean
      publish_docker:
        required: false
        default: true
        type: boolean
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  publish_github:
    name: Create Release on GitHub
    runs-on: ubuntu-latest
    if: ${{ inputs.publish_github }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Create a new release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  publish_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ inputs.publish_docker }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: novosadkry/novaxis
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern=v{{version}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
